# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Cathode"
license = "MIT"
licenselink = "https://github.com/siawyoung/cathode/blob/master/LICENSE.md"
description = "A Hugo theme for displaying visual content in a grid-like fashion."
homepage = "https://github.com/siawyoung/cathode"
tags = ["albums", "music", "grid"]
features = ["responsive", "colourful"]
min_version = 0.14

[author]
  name = "Lau Siaw Young"
  homepage = "http://siawyoung.com"